version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"    # Exposing MongoDB on the default port
    volumes:
      - ./data/db:/data/db  # Persist MongoDB data on the local machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # MongoDB root user
      MONGO_INITDB_ROOT_PASSWORD: example  # MongoDB root password

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    ports:
      - "8081:8081"  # Exposing Mongo Express on port 8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
